parameters:
    # Define the default URI used for URL generation in non-HTTP contexts.
    env(DEFAULT_URI): 'http://localhost'

framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(string:DEFAULT_URI)%'

when@prod:
    framework:
        router:
            strict_requirements: null
